### ISSUE TITLE
SwiftyButton does not work with Carthage

### ISSUE THREAD

**Issue by rnitame** [TakeScoop/SwiftyButton#10]
```
$ carthage update --platform iOS
*** Fetching SwiftyButton
*** Fetching SwiftyJSON
*** Fetching Alamofire
*** Checking out Alamofire at "4.3.0"
*** Checking out SwiftyButton at "0.6.0"
*** Downloading SwiftyJSON.framework binary at "3.1.4"
*** xcodebuild output can be found in /var/folders/xl/gxvzy0ws6q3bs_p2q2k69mg00000gn/T/carthage-xcodebuild.CKTxod.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Skipped building SwiftyButton due to the error:
Dependency "SwiftyButton" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at Optional("https://github.com/TakeScoop/SwiftyButton/issues/new")
```

**Comment by perryprog** [comment]
Bump? I kind of need to use this library and I just switched from CocoaPods to Carthage.

**Comment by rnitame** [comment]
@perryprog Thanks for reply. 
I changed it from carthage to cocoapods.

**Comment by perryprog** [comment]
@rnitame you should probably leave it open since the problem still exists. Just so TakeScoop knows that people still have a problem with that.

**Comment by rnitame** [comment]
@perryprog sure. I've reopened this issue

**Comment by ldiqual** [comment]
@rnitame @perryprog  I've created a blank project and added the following Cartfile:

```
github "TakeScoop/SwiftyButton" "master"
```

Then ran 

```
$ carthage update --platform iOS

*** Fetching SwiftyButton
*** Checking out SwiftyButton at "211690b4f9fdf0bbeefa086d6f527654e76e5022"
*** xcodebuild output can be found in /var/folders/ns/__x7qnxd17b_mg_wzntwzm8c0000gn/T/carthage-xcodebuild.zsW6Mp.log
*** Building scheme "SwiftyButton" in SwiftyButton.xcworkspace
```

I drag-dropped the resulting framework, imported the framework, created a button and compiled the whole project: everything worked fine.

Am I missing something here? I used carthage 0.20.1.

**Comment by rnitame** [comment]
@ldiqual It worked in own environment! XD
![image](https://cloud.githubusercontent.com/assets/4950792/24901875/5dd13ef2-1ee3-11e7-8a0f-6fa2d0cd513d.png)

**Comment by perryprog** [comment]
Well then. I'll try that, but right now I'm running into a problem with submitting my app to the appnstore. (Incorrect bundle ID or something.) https://github.com/Carthage/Carthage/issues/1834


That's my shameless plug of the day.

**Comment by ldiqual** [comment]
Looks like it works now so I'm gonna close the issue. Feel free to ask for a reopen if you still run into issues. Thanks!
