### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by WillMays1** [TakeScoop/SwiftyButton#13]
Will we see an update for swift 4 anytime in the future?

**Comment by mituljindal** [comment]
Any news on swift 4 update? It gives error on build.

**Comment by ldiqual** [comment]
Sorry, totally forgot to mention it, there's a `lois-swift4` branch that we've been using in prod for a bit. I'll create an official version soon but I would recommended using `lois-swift4` in your podfile for now.

**Comment by ldiqual** [comment]
SwiftyButton 0.8.0 is now available on cocoapods and adds Swift 4 support: https://cocoapods.org/pods/SwiftyButton
Thanks for your patience!
