### ISSUE TITLE
Bottom of button text cut off when using Font Awesome

### ISSUE THREAD

**Issue by squeeish** [TakeScoop/SwiftyButton#3]
I'm new to iOS programming. I've noticed that if I have a prefix containing the letters "g", "p", etc, the bottom part of the text is cut off when I use font awesome icons by Vaberer's Font-Awesome-Swift library. 

![Imgur](http://i.imgur.com/LJlKAif.png)

Do you have any hints to what might be causing this problem?

**Comment by ldiqual** [comment]
@squeeish Looks like a [titleEdgeInsets](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIButton_Class/#//apple_ref/occ/instp/UIButton/titleEdgeInsets) issue to me. SwiftyButton plays with title insets internally so I'm not too surprised.

Would you mind sharing a code example so I can investigate further? Thank you!

**Comment by squeeish** [comment]
@ldiqual thanks! It's pretty simple:

https://github.com/Vaberer/Font-Awesome-Swift adds functions to UIButton, which I'm using as follows:

```
buttonLogin.setFAText(prefixText: "Log in ", icon: FAType.FALock, 
    postfixText: "", size: 14, forState: .Normal)
```

I took a look at Font-Awesome-Swift's library, this is the code of `.setFAText`. I'm not sure how to investigate further from here.

```
func setFAText(prefixText prefixText: String, icon: FAType?, postfixText: String, size: CGFloat?, forState state: UIControlState, iconSize: CGFloat? = nil) {

        if let titleLabel = titleLabel {

            FontLoader.loadFontIfNeeded()
            let textFont = UIFont(name: FAStruct.FontName, size: size ?? titleLabel.font.pointSize)
            assert(textFont != nil, FAStruct.ErrorAnnounce)
            titleLabel.font = textFont!

            let textAttribute = [NSFontAttributeName : titleLabel.font]
            let myString = NSMutableAttributedString(string: prefixText, attributes: textAttribute )

            if let iconText = icon?.text {

                let iconFont = UIFont(name: FAStruct.FontName, size: iconSize ?? size ?? titleLabel.font.pointSize)!
                let iconAttribute = [NSFontAttributeName : iconFont]

                let iconString = NSAttributedString(string: iconText, attributes: iconAttribute)
                myString.appendAttributedString(iconString)
            }

            let postfixString = NSAttributedString(string: postfixText)
            myString.appendAttributedString(postfixString)

            setAttributedTitle(myString, forState: state)
        }
    }
```

**Comment by ldiqual** [comment]
@squeeish I played a bit with your code and the library you linked to, and it turns out that using a regular `UIButton` causes the same issue:

![image](https://cloud.githubusercontent.com/assets/941453/12104791/b2e85e4a-b303-11e5-9594-70520ff6ad0f.png)

So this bug is unrelated to SwiftyButton. From what I saw, it only happens when using the FA font, not when using the system font, so there's something wrong there (probably the line height). I'd suggest that you open an issue on the library's issue tracker.

Let me know if you need anything else! Closing this.

**Comment by squeeish** [comment]
I will. Thanks for taking the time to help me out!

**Comment by squeeish** [comment]
For anyone else who needs a solution to this, see https://github.com/Vaberer/Font-Awesome-Swift/issues/20
