### ISSUE TITLE
Put Purelayout out of this library.

### ISSUE THREAD

**Issue by Joker666** [TakeScoop/SwiftyButton#5]
Such an awesome library, but wasted for fancy inclusion of another library that adds no value and can be coded with NSLayoutContrstaints. Please keep the code clean. The point of libraries are to keep third party dependency as less as possible.

The obvious answer would be, no you don't have to use my library, find another one or write it yourself. Well thats what I am doing. But just to make my point clear, just coz it your preference to use autolayout with PureLayout forces the users of this library to have that dependency. It is **NOT** required.

**Comment by rgnlax** [comment]
+1

**Comment by ldiqual** [comment]
@Joker666 @rgnlax Just fixed it in 0.6.0. Check it out!
