### ISSUE TITLE
Can't create button in IB

### ISSUE THREAD

**Issue by perryprog** [TakeScoop/SwiftyButton#9]
When trying to create a button in IB following the instructions on the README I get the following error:
```
file:///Users/$USER/Path/To/My/Project/Base.lproj/Main.storyboard: warning: IB Designables: Using class UIButton for object with custom class because the class PressableButton does not exist
```

I installed via Coccoapods `pod 'SwiftyButton'` and when typing the buttons class in IB it does autocomplete it and offers it as an option in the list of choices.

<img width="253" alt="screen shot 2017-02-06 at 2 44 43 pm" src="https://cloud.githubusercontent.com/assets/12972285/22663507/d9b7f01a-ec7a-11e6-9656-1f8298540dc5.png">

Any help is appreciated, thanks!

**EDIT:** To be clear, I did set the button type to custom.

**Comment by perryprog** [comment]
Oh that's lovely. I never set the Module to SwiftyButton.

**Comment by ldiqual** [comment]
Fixed in the readme: https://github.com/TakeScoop/SwiftyButton#interface-builder-storyboardxib. Thanks for reporting!

**Comment by perryprog** [comment]
No problem.
